# Generated by Django 2.0.2 on 2018-02-03 08:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('domain', models.TextField()),
                ('path', models.TextField()),
                ('rank', models.IntegerField()),
                ('in_links', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('out_links', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('text', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('currencies', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('sentiment', models.IntegerField()),
            ],
        ),
    ]
